-- 183_varsity_roster_aiden_ross.sql
--
-- Adds #67 Aiden Ross, junior, to the 2026-27 varsity roster. Jeremy 2026-09-06:
-- "add #67 Aiden Ross - Junior (He is probably also on the JV roster, that is
-- okay)". Varsity goes 45 -> 46 players.
--
-- ── HE IS ALREADY ON JV, AND THAT IS DELIBERATE, NOT A DUPLICATE ──
-- `/roster/jv` carries him as **#66 Aiden Robert Ross, OL** (seeded by 166 from
-- the coaching staff's JV file). Playing up is normal and Jeremy said so
-- explicitly. Do NOT "deduplicate" these two rows -- they are two rosters, and
-- deleting the JV one would silently drop him off the JV page.
--
-- ⚠️ THREE THINGS ABOUT HIM DIFFER BETWEEN THE TWO ROWS. Each is intentional:
--
-- 1. JERSEY 67 HERE, 66 ON JV. Varsity #66 is already Kaeden Frazier, so 67 is
--    not a typo for 66 -- it cannot be 66 on this roster. A player carrying
--    different numbers at two levels is ordinary. Jeremy gave 67 for varsity.
--
-- 2. "Aiden Ross" HERE, "Aiden Robert Ross" ON JV. That is a difference between
--    the two source sheets, not a data error: in the coaches' workbook the JV
--    sheet lists full legal names with middle names for EVERY player, and the
--    varsity sheet lists none for ANY of its 45. Short form is what belongs in
--    the varsity block. It is also how the 2025-26 JV roster listed him.
--
-- 3. POSITION IS NULL HERE, 'OL' ON JV. ⚠️ NOT AN OVERSIGHT AND NOT A GAP TO
--    FILL BY INFERENCE. Jeremy supplied number, name and grade; he did not
--    supply a position, and copying one across levels is a guess about where a
--    coach plays him on a different team. It renders as an em-dash, which is the
--    standing deliberate behaviour for missing roster data (Jeremy 2026-08-26:
--    "maybe it will make the coaches want to step up their game on getting me
--    data!"). Raised with Jeremy 2026-09-06, WHO CONFIRMED OL -- migration 184
--    sets it. This comment stands as the record of why it was not assumed here.
--    🚫 This is NOT the height/weight rule -- those are suppressed on Coach's
--    instruction; Position and Grade point the opposite way and still render.
--
-- ── sort_order IS RECOMPUTED, NOT HAND-PATCHED ──
-- 159's convention as 171 applied it: dense from 1, ordered by the LEADING
-- number of `jersey_number`, so '5/2' sorts as 5 and '84/80' as 84. 67 lands
-- between #66 Frazier and #71 Omagbon, shifting the six players above him by
-- one. Seven rows differ afterwards: the insert plus those six.
--
-- The migration asserts the recomputation is a no-op for everyone else first --
-- i.e. that the existing 45 were already in leading-number order -- so a silent
-- reshuffle of the whole roster cannot hide inside this change.
--
-- ⚠️ THE PRINT-VIEW PDF IS A SECOND ARTEFACT AND IS **NOT** DONE BY THIS
-- MIGRATION. `/roster/varsity` Print View serves
-- `documents/rosters/varsity-2026-r3.pdf`, generated by
-- `scripts/make-varsity-roster-pdf.py` from the coaches' workbook
-- (`roster_pdf/source/Varsity McNeil Roster 2026.xlsx`, gitignored, only on
-- Jeremy's disk). Migration 171 and the 176 postmortem both say it: a roster
-- change is two artefacts. Migration 186 repoints the row at r4.
--
-- DB-ONLY, NO DEPLOY. /roster/* renders on demand.
--
-- Rollback: 183_rollback.sql

begin;

do $$
declare n int; rid uuid;
begin
  select id into rid from rosters
   where year = '2026-27' and team_level = 'varsity' and team_designation is null;
  if rid is null then raise exception '2026-27 varsity roster not found'; end if;

  select count(*) into n from players where roster_id = rid;
  if n <> 45 then raise exception 'expected 45 varsity players, found %', n; end if;

  select count(*) into n from players
   where roster_id = rid and jersey_number = '67';
  if n <> 0 then raise exception 'varsity #67 already exists (already applied?)'; end if;

  -- 67 must not collide with the leading number of any existing jersey.
  select count(*) into n from players
   where roster_id = rid and split_part(jersey_number, '/', 1) = '67';
  if n <> 0 then raise exception '% existing varsity player(s) already lead with 67', n; end if;

  -- The 45 existing rows must already be in leading-number order, or the
  -- recomputation below would quietly reorder the whole roster.
  select count(*) into n from (
    select p.sort_order,
           row_number() over (order by split_part(p.jersey_number, '/', 1)::int) as rn
      from players p where p.roster_id = rid
  ) t where t.sort_order <> t.rn;
  if n <> 0 then
    raise exception '% varsity row(s) are not in leading-number sort order; stopping', n;
  end if;
end $$;

insert into players (roster_id, jersey_number, first_name, last_name, position, grade, sort_order, active)
select r.id, '67', 'Aiden', 'Ross', null, 'Jr.', 0, true
  from rosters r
 where r.year = '2026-27' and r.team_level = 'varsity' and r.team_designation is null;

with ordered as (
  select p.id,
         row_number() over (order by split_part(p.jersey_number, '/', 1)::int) as rn
    from players p
    join rosters r on r.id = p.roster_id
   where r.year = '2026-27' and r.team_level = 'varsity' and r.team_designation is null
)
update players p
   set sort_order = o.rn, updated_at = now()
  from ordered o
 where o.id = p.id and p.sort_order is distinct from o.rn;

do $$
declare n int; rid uuid;
begin
  select id into rid from rosters
   where year = '2026-27' and team_level = 'varsity' and team_designation is null;

  select count(*) into n from players where roster_id = rid;
  if n <> 46 then raise exception 'expected 46 varsity players, found %', n; end if;

  select count(*) into n from players
   where roster_id = rid and jersey_number = '67'
     and first_name = 'Aiden' and last_name = 'Ross'
     and grade = 'Jr.' and position is null and active and sort_order = 40;
  if n <> 1 then raise exception 'Aiden Ross row is not as intended'; end if;

  -- sort_order is dense 1..46 with no gaps or duplicates.
  select count(*) into n from (
    select sort_order, row_number() over (order by split_part(jersey_number, '/', 1)::int) as rn
      from players where roster_id = rid
  ) t where t.sort_order <> t.rn;
  if n <> 0 then raise exception '% varsity row(s) out of order after recompute', n; end if;

  select count(distinct sort_order) into n from players where roster_id = rid;
  if n <> 46 then raise exception 'duplicate sort_order values (% distinct)', n; end if;

  -- 171's finding: the four slash jerseys are real home/away pairs and must
  -- survive any roster edit untouched.
  select count(*) into n from players
   where roster_id = rid and jersey_number like '%/%';
  if n <> 4 then raise exception 'expected 4 slash jerseys, found %', n; end if;

  -- He must still be on JV as well. Removing him there is not part of this.
  select count(*) into n from players p
    join rosters r on r.id = p.roster_id
   where r.year = '2026-27' and r.team_level = 'jv'
     and p.first_name = 'Aiden' and p.last_name = 'Robert Ross' and p.jersey_number = '66';
  if n <> 1 then raise exception 'the JV Aiden Robert Ross row was disturbed'; end if;
end $$;

commit;
